<?php
/**
 * @author      Tsvetan Stoychev <tsvetan.stoychev@extendix.com>
 * @website     http://www.extendix.com
 * @license     http://opensource.org/licenses/osl-3.0.php Open Software Licence 3.0 (OSL-3.0)
 */

/** @var $this Extendix_SpeedySimpleShipping_Block_Adminhtml_BillOfLading_Sender */

$_senderHelper = $this->getSenderHelper();
?>

<div class="entry-edit">
    <div class="field-row grid">
        <table cellspacing="0" class="data">
            <thead>
                <tr class="headings">
                    <th colspan="2"><?php echo $this->__('Sender info') ?></th>
                </tr>
            </thead>
            <tfoot>
                <tr>
                    <td width="20%"><?php echo $this->__('Api Username:') ?></td>
                    <td><input class="input-text" value="<?php echo $_senderHelper->getApiUsername($this->getRequest()->getParam('store_id')); ?>" disabled="disabled" /></td>
                </tr>
                <tr>
                    <td width="20%"><?php echo $this->__('Name:') ?></td>
                    <td><input class="input-text" value="<?php echo $_senderHelper->getName(); ?>" /></td>
                </tr>
                <tr>
                    <td width="20%"><?php echo $this->__('Phone:') ?></td>
                    <td><input class="input-text" value="<?php echo $_senderHelper->getPhone() ?>" /></td>
                </tr>
                <tr>
                    <td width="20%"><?php echo $this->__('Site:') ?></td>
                    <td><input class="input-text" value="<?php echo $_senderHelper->getSite(); ?>" /></td>
                </tr>
            </tfoot>
        </table>
    </div>
</div>
