<?php
/**
 * @author      Tsvetan Stoychev <tsvetan.stoychev@bulgento.com>
 * @website     http://www.bulgento.com
 * @license     http://opensource.org/licenses/osl-3.0.php Open Software Licence 3.0 (OSL-3.0)
 */

/** @var $this BulGento_SpeedySimpleShipping_Block_Adminhtml_BillOfLading_Sender */

$_senderHelper = $this->getSenderHelper();
?>

<div class="field-row grid">
    <table cellspacing="0" class="data">
        <thead>
        <tr class="headings">
            <th><?php echo $this->__('Sender info:') ?></th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td>
                <ul>
                    <li><?php echo $this->__('Api Username:') ?> <input value="<?php echo $_senderHelper->getApiUsername($this->getRequest()->getParam('store_id')); ?>" disabled="disabled" /></li>
                    <li><?php echo $this->__('Name:') ?> <input value="<?php echo $_senderHelper->getName(); ?>" /></li>
                    <li><?php echo $this->__('Phone:') ?> <input value="<?php echo $_senderHelper->getPhone() ?>" /></li>
                    <li><?php echo $this->__('Site:') ?> <input value="<?php echo $_senderHelper->getSite(); ?>" /></li>
                </ul>
            </td>
        </tr>
        </tbody>
    </table>
</div>
