<?php
/**
 * @author      Tsvetan Stoychev <tsvetan.stoychev@extendix.com>
 * @website     http://www.extendix.com
 * @license     http://opensource.org/licenses/osl-3.0.php Open Software Licence 3.0 (OSL-3.0)
 */

$optionArray = $this->getDateOptions();
?>
<?php if(!empty($optionArray)) : ?>
    <select name="picking[TakingDate]" class="select" style="width:90px">
        <?php foreach($optionArray as $date) : ?>
            <option value="<?php echo $date; ?>"><?php echo $date; ?></option>
        <?php endforeach; ?>
    </select>
<?php else :  ?>
    <?php echo $this->__('No tacking dates found so far. Please choose a site to get a list of all available tacking dates!') ?>
<?php endif; ?>